version: '3.8'

services:
  server-config:
    build:
      context: "./server-config"
      dockerfile: Dockerfile
    ports:
      - "${CONFIGSERVER_PORT}:${CONFIGSERVER_PORT}"
    env_file:
      - ./configserver.env #contains encryption key to encode sensitive properties from fetched config

  discover-server:
    build:
      context: "./discover-server"
      dockerfile: Dockerfile
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"

  kafka:
    image: apache/kafka:4.2.0
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ' #hardcoded for local dev purposes

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  users-service:
    build:
      context: "./jpaapi"
      dockerfile: Dockerfile

  gateway:
    build:
      context: "./gateway"
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"