version: '3.8'

services:
  server-config:
    build:
      context: "./server-config"
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - ./configserver.env

  discover-server:
    build:
      context: "./discover-server"
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
